---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-appmesh
  region: us-east-1
vpc:
  id: "vpc-06948c85f80da5f63"
  cidr: "10.100.0.0/16"
  subnets:
    public:
      us-east-1a:
        id: "subnet-0b7f416ee5bd8f138"
        cidr: "10.100.3.0/24"
      us-east-1c:
        id: "subnet-023d28a91e9332a35"
        cidr: "10.100.0.0/24"  
    private:
      us-east-1a:
        id: "subnet-077945d62638c1b6a"
        cidr: "10.100.4.0/24"
      us-east-1c:
        id: "subnet-01dbf269b1fc50230"
        cidr: "10.100.1.0/24"  
managedNodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 3
    volumeSize: 100
    privateNetworking: true
    ssh: # use existing EC2 key
      allow: true
      publicKeyName: yfwang-Virginia
      sourceSecurityGroupIds: ["sg-08b9cc2dcea752c25", "sg-08e76e4b56c1516bb"]
      enableSsm: true