---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: my-apps
spec:
  selector:
    matchLabels:
      tier: backend
      track: stable
      app: my-app-1
  replicas: 3
  template:
    metadata:
      labels:
        app: my-app-1
        tier: backend
        track: stable
    spec:
      containers:
        - name: hello
          image: nginx:1.14.2
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service-a
  namespace: my-apps
spec:
  selector:
    app: my-app-1
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
